### ISSUE TITLE
AP/VLAN Capability

### ISSUE THREAD

**Issue by part1cleth1ef** [openwrt-ipq60xx/openwrt#11]
Hello,
This repo is for ipq60xx however doesn't support the AP/VLAN capability that QSDK supports (the default firmware on the glaxt1800) which I've been unable to get on any newer clean firmwares. Are there any plans to support this??
Thanks!

**Comment by pexcn** [comment]
Try this artifacts: https://github.com/openwrt-ipq60xx/ci/actions/runs/9595098490
