### ISSUE TITLE
Considering adding ath11k wifi nss?

### ISSUE THREAD

**Issue by breeze303** [openwrt-ipq60xx/openwrt#12]
https://github.com/qosmio/openwrt-ipq/commit/01dfffd16b0ff525aaabc98aa1372c41b3db552c
Currently this is an experimental wifi nss, the bug encountered is that after adding it ath11k can't find the memory can't start, but can boot normally, if you are interested you can join the test, it should be a fun thing to do!

**Comment by pexcn** [comment]
Nice work. Now the JiaY-shi version also supports it, I'll check it out.

**Comment by breeze303** [comment]
[https://github.com/breeze303/openwrt-6.x/commit/79925a21734c44ffc3a6a2398eef69102aa2e961](url) Near perfect wifi nss

**Comment by pexcn** [comment]
Nice work. Have you tried using `CONFIG_ATH11K_MEM_PROFILE_1G`? After I using it it seems that boot loop.

**Comment by breeze303** [comment]
> Nice work. Have you tried using `CONFIG_ATH11K_MEM_PROFILE_1G`? After I using it it seems that boot loop.

Do not select 1G or 256MB, only 512MB is normal.

**Comment by pexcn** [comment]
Okay, done!
