### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by pexcn** [openwrt-ipq60xx/openwrt#8]
- [x] **Issue 1:** WiFi clients upload speed is only half of download speed.
- [ ] **Issue 2:** Kernel report this message, maybe take a WiFi speed test or roaming between two APs can reproduce it
```txt
ath11k c000000.wifi: failed to flush transmit queue, data pkts pending 1
```
- [ ] **Issue 3:** Enabling flow offloading will cause some devices connected to its WiFi to be unable to access the Internet (wired connections seems not appear to be affected), maybe it has something to do with NSS? Or I need to install `iptables` package? I am not sure.
~BTW, when flow offloading is enabled, the upload speed of WiFi speed test can reach more than 800Mbps, but when it is not enabled, it is less than 500Mbps.~

**Comment by pexcn** [comment]
Rather than adding support for low-memory devices, I think solving the above issues is more urgent.

CC: @breeze303 @proxer05

**Comment by try496** [comment]
我的ax5 重启后mac地址会随机 但是我发现wifi的mac地址不会 请问你的也会这样吗 我的是1g 大分区

**Comment by try496** [comment]
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x51af8014]
[    0.000000] Linux version 6.1.82 (builder@c77fb7040460) (aarch64-openwrt-linux-musl-gcc (OpenWrt GCC 12.3.0 r25652-20240322) 12.3.0, GNU ld (GNU Binutils) 2.40.0) #0 SMP PREEMPT Thu Mar 21 15:16:53 2024
[    0.000000] Machine model: Redmi AX5
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000040000000-0x000000007fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040000000-0x0000000040ffffff]
[    0.000000]   node   0: [mem 0x0000000041000000-0x000000004a0fffff]
[    0.000000]   node   0: [mem 0x000000004a100000-0x00000000501fffff]
[    0.000000]   node   0: [mem 0x0000000050200000-0x000000007fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040000000-0x000000007fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv1.0 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: MIGRATE_INFO_TYPE not supported.
[    0.000000] psci: SMC Calling Convention v1.0
[    0.000000] percpu: Embedded 18 pages/cpu s35944 r8192 d29592 u73728
[    0.000000] pcpu-alloc: s35944 r8192 d29592 u73728 alloc=18*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 258048
[    0.000000] Kernel command line: console=ttyMSM0,115200n8 ubi.mtd=rootfs root=mtd:ubi_rootfs rootfstype=squashfs rootwait root=/dev/ubiblock0_1 swiotlb=1 coherent_pool=2M
[    0.000000] Dentry cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 898820K/1048576K available (9408K kernel code, 962K rwdata, 1508K rodata, 1408K init, 308K bss, 149756K reserved, 0K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] 	Trampoline variant of Tasks RCU enabled.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 100 jiffies.
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: 0xffffffc008462510
[    0.000000] GICv2m: range[mem 0x0b00a000-0x0b00affc], SPI[448:479]
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 and mmio timer(s) running at 24.00MHz (virt/virt).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000001] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000072] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=24000)
[    0.000085] pid_max: default: 32768 minimum: 301
[    0.000549] Mount-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.000565] Mountpoint-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.002521] cblist_init_generic: Setting adjustable number of callback queues.
[    0.002530] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.002628] cblist_init_generic: Setting adjustable number of callback queues.
[    0.002633] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.002831] rcu: Hierarchical SRCU implementation.
[    0.002835] rcu: 	Max phase no-delay instances is 400.
[    0.003572] smp: Bringing up secondary CPUs ...
[    0.004261] Detected VIPT I-cache on CPU1
[    0.004400] CPU1: Booted secondary processor 0x0000000001 [0x51af8014]
[    0.005068] Detected VIPT I-cache on CPU2
[    0.005170] CPU2: Booted secondary processor 0x0000000002 [0x51af8014]
[    0.005827] Detected VIPT I-cache on CPU3
[    0.005922] CPU3: Booted secondary processor 0x0000000003 [0x51af8014]
[    0.005990] smp: Brought up 1 node, 4 CPUs
[    0.005999] SMP: Total of 4 processors activated.
[    0.006005] CPU features: detected: 32-bit EL0 Support
[    0.006010] CPU features: detected: CRC32 instructions
[    0.006084] CPU features: emulated: Privileged Access Never (PAN) using TTBR0_EL1 switching
[    0.006091] CPU: All CPU(s) started at EL1
[    0.006094] alternatives: applying system-wide alternatives
[    0.015510] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
[    0.015537] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.015764] pinctrl core: initialized pinctrl subsystem
[    0.016925] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.017863] DMA: preallocated 2048 KiB GFP_KERNEL pool for atomic allocations
[    0.018212] DMA: preallocated 2048 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.018544] DMA: preallocated 2048 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.018930] thermal_sys: Registered thermal governor 'step_wise'
[    0.019147] cpuidle: using governor menu
[    0.019458] ASID allocator initialised with 65536 entries
[    0.069322] qcom,cpr4-apss-regulator b018000.cpr4-ctrl: CPR valid fuse count: 4
[    0.077739] cryptd: max_cpu_qlen set to 1000
[    0.079841] SCSI subsystem initialized
[    0.080032] usbcore: registered new interface driver usbfs
[    0.080085] usbcore: registered new interface driver hub
[    0.080123] usbcore: registered new device driver usb
[    0.080429] qcom_scm: convention: smc arm 64
[    0.081700] s2: Bringing 0uV into 725000-725000uV
[    0.082471] clocksource: Switched to clocksource arch_sys_counter
[    0.082832] l2: Bringing 0uV into 1800000-1800000uV
[    0.083006] qcom_rpm_smd_regulator remoteproc:glink-edge:rpm-requests:regulators: Supply for l2 (l2) resolved to itself
[    0.083728] NET: Registered PF_INET protocol family
[    0.083904] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.085252] tcp_listen_portaddr_hash hash table entries: 512 (order: 1, 8192 bytes, linear)
[    0.085280] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.085296] TCP established hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.085383] TCP bind hash table entries: 8192 (order: 6, 262144 bytes, linear)
[    0.085681] TCP: Hash tables configured (established 8192 bind 8192)
[    0.085801] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.085840] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.086043] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.086079] PCI: CLS 0 bytes, default 64
[    0.088229] workingset: timestamp_bits=46 max_order=18 bucket_order=0
[    0.093555] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.093568] jffs2: version 2.2 (NAND) (SUMMARY) (LZMA) (RTIME) (CMODE_PRIORITY) (c) 2001-2006 Red Hat, Inc.
[    0.153644] bam-dma-engine 704000.dma-controller: num-channels unspecified in dt
[    0.153660] bam-dma-engine 704000.dma-controller: num-ees unspecified in dt
[    0.159159] Serial: 8250/16550 driver, 2 ports, IRQ sharing disabled
[    0.159928] msm_serial 78b1000.serial: msm_serial: detected port #0
[    0.159966] msm_serial 78b1000.serial: uartclk = 1843199
[    0.160057] 78b1000.serial: ttyMSM0 at MMIO 0x78b1000 (irq = 22, base_baud = 115199) is a MSM
[    0.160086] msm_serial: console setup on port #0
[    0.823222] printk: console [ttyMSM0] enabled
[    0.828496] msm_serial: driver initialized
[    0.837630] loop: module loaded
[    0.839144] Could not find a valid ONFI parameter page, trying bit-wise majority to recover it
[    0.839711] ONFI parameter recovery failed, aborting
[    0.848317] nand: device found, Manufacturer ID: 0xc8, Chip ID: 0xa1
[    0.853400] nand: ESMT NAND 128MiB 1,8V 8-bit
[    0.859730] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    0.879601] i2c_dev: i2c /dev entries driver
[    0.884638] sdhci: Secure Digital Host Controller Interface driver
[    0.884687] sdhci: Copyright(c) Pierre Ossman
[    0.889742] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.897915] remoteproc remoteproc0: releasing cd00000.remoteproc
[    0.902826] NET: Registered PF_INET6 protocol family
[    0.906956] Segment Routing with IPv6
[    0.910862] In-situ OAM (IOAM) with IPv6
[    0.914443] NET: Registered PF_PACKET protocol family
[    0.918425] Bridge firewalling registered
[    0.923428] l2tp_core: L2TP core driver, V2.0
[    0.927320] l2tp_netlink: L2TP netlink interface
[    0.931688] 8021q: 802.1Q VLAN Support v1.8
[    0.972308] qcom,cpr4-apss-regulator b018000.cpr4-ctrl: CPR valid fuse count: 4
[    0.972612] cpr4_ipq807x_apss_read_fuse_data: apc_corner: speed bin = 0
[    0.978459] cpr4_ipq807x_apss_read_fuse_data: apc_corner: CPR fusing revision = 2
[    0.985064] cpr4_ipq807x_apss_read_fuse_data: apc_corner: CPR misc fuse value = 0
[    0.992786] cpr4_ipq807x_apss_read_fuse_data: apc_corner: Voltage boost fuse config = 0 boost = disable
[    1.000216] cpr3_mem_acc_init: apc: not using memory accelerator regulator
[    1.009348] cpr4_ipq807x_apss_calculate_open_loop_voltages: apc_corner: fused      SVS: open-loop= 675000 uV
[    1.016293] cpr4_ipq807x_apss_calculate_open_loop_voltages: apc_corner: fused      NOM: open-loop= 787500 uV
[    1.026276] cpr4_ipq807x_apss_calculate_open_loop_voltages: apc_corner: fused    TURBO: open-loop= 850000 uV
[    1.036084] cpr4_ipq807x_apss_calculate_open_loop_voltages: apc_corner: fused   STURBO: open-loop= 900000 uV
[    1.045921] cpr4_ipq807x_apss_calculate_target_quotients: apc_corner: fused      SVS: quot[ 7]= 609, quot_offset[ 7]=   0
[    1.055712] cpr4_ipq807x_apss_calculate_target_quotients: apc_corner: fused      NOM: quot[ 7]= 806, quot_offset[ 7]= 195
[    1.066555] cpr4_ipq807x_apss_calculate_target_quotients: apc_corner: fused    TURBO: quot[ 7]= 908, quot_offset[ 7]= 100
[    1.077493] cpr4_ipq807x_apss_calculate_target_quotients: apc_corner: fused   STURBO: quot[ 7]= 981, quot_offset[ 7]=  70
[    1.088722] cpr3_regulator_init_ctrl: apc: Default CPR mode = closed-loop
[    1.091478] Could not find a valid ONFI parameter page, trying bit-wise majority to recover it
[    1.106238] ONFI parameter recovery failed, aborting
[    1.114676] nand: device found, Manufacturer ID: 0xc8, Chip ID: 0xa1
[    1.119763] nand: ESMT NAND 128MiB 1,8V 8-bit
[    1.126092] nand: 128 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    1.130684] 13 qcomsmem partitions found on MTD device qcom_nand.0
[    1.137821] Creating 13 MTD partitions on "qcom_nand.0":
[    1.143978] 0x000000000000-0x000000180000 : "0:sbl1"
[    1.151512] 0x000000180000-0x000000280000 : "0:mibib"
[    1.155894] 0x000000280000-0x000000600000 : "0:qsee"
[    1.163114] 0x000000600000-0x000000680000 : "0:devcfg"
[    1.165371] 0x000000680000-0x000000700000 : "0:rpm"
[    1.170349] 0x000000700000-0x000000780000 : "0:cdt"
[    1.175115] 0x000000780000-0x000000800000 : "0:appsblenv"
[    1.180008] 0x000000800000-0x000000980000 : "0:appsbl"
[    1.186499] 0x000000980000-0x000000a00000 : "0:art"
[    1.190602] 0x000000a00000-0x000000a80000 : "bdata"
[    1.195364] 0x000000a80000-0x000000b00000 : "crash"
[    1.200172] 0x000000b00000-0x000000b80000 : "crash_syslog"
[    1.205105] 0x000000b80000-0x000007b80000 : "rootfs"
[    1.313153] mtd: setting mtd12 (rootfs) as root device
[    1.313530] mtdsplit: no squashfs found in "rootfs"
[    1.323771] cpufreq: cpufreq_online: CPU0: Running at unlisted initial frequency: 799999 KHz, changing to: 864000 KHz
[    1.326596] remoteproc remoteproc0: cd00000.remoteproc is available
[    1.333978] ubi0: attaching mtd12
[    1.963698] ubi0: scanning is finished
[    1.971517] ubi0: attached mtd12 (name "rootfs", size 112 MiB)
[    1.971558] ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
[    1.976266] ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
[    1.983113] ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
[    1.989974] ubi0: good PEBs: 896, bad PEBs: 0, corrupted PEBs: 0
[    1.996743] ubi0: user volume: 3, internal volumes: 1, max. volumes count: 128
[    2.003000] ubi0: max/mean erase counter: 2/1, WL threshold: 4096, image sequence number: 1535487394
[    2.010029] ubi0: available PEBs: 0, total reserved PEBs: 896, PEBs reserved for bad PEB handling: 20
[    2.019322] ubi0: background thread "ubi_bgt0d" started, PID 487
[    2.020223] block ubiblock0_1: created from ubi0:1(rootfs)
[    2.037701] VFS: Mounted root (squashfs filesystem) readonly on device 254:0.
[    2.038395] Freeing unused kernel memory: 1408K
[    2.049589] Run /sbin/init as init process
[    2.049607]   with arguments:
[    2.049610]     /sbin/init
[    2.049613]   with environment:
[    2.049615]     HOME=/
[    2.049617]     TERM=linux
[    2.283912] init: Console is alive
[    2.284089] init: - watchdog -
[    2.590481] random: crng init done
[    3.056914] kmodloader: loading kernel modules from /etc/modules-boot.d/*
[    3.115494] ssdk_dt_parse_interrupt[935]:INFO:intr-gpio does not exist
[    3.440793] __adpt_hppe_uniphy_psgmii_mode_set[1156]:INFO:uniphy 0 psgmii channel selection
[    3.549563] regi_init[3603]:INFO:Initializing HPPE Done!!
[    3.549671] regi_init[3662]:INFO:qca-ssdk module init succeeded!
[    3.556238] EDMA ver 1 hw init
[    3.560232] EDMA HW Reset completed succesfully
[    3.562901] Num rings - TxDesc:1 (23-23) TxCmpl:1 (23-23)
[    3.567306] RxDesc:1 (15-15) RxFill:1 (7-7)
[    3.573281] GMAC2(ffffff8003b82900) Invalid MAC@ - using 46:62:cf:1b:96:ad
[    3.576865] dp2: ppe offload disabled: 0 for macid 2
[    3.746410] GMAC3(ffffff8003b85900) Invalid MAC@ - using 66:64:56:79:98:ed
[    3.746478] dp3: ppe offload disabled: 0 for macid 3
[    3.769932] GMAC4(ffffff80049f2900) Invalid MAC@ - using 8e:ba:bb:91:d4:26
[    3.769976] dp4: ppe offload disabled: 0 for macid 4
[    3.829789] GMAC5(ffffff80049f5900) Invalid MAC@ - using 42:7a:c5:f6:11:60
[    3.829833] dp5: ppe offload disabled: 0 for macid 5

**Comment by pexcn** [comment]
> 我的ax5 重启后mac地址会随机 但是我发现wifi的mac地址不会 请问你的也会这样吗 我的是1g 大分区

用最新 release 里的固件，一切正常

**Comment by try496** [comment]
重新刷回官方固件 在刷回openwrt 问题依旧  最后用刷回官方备份的art分区文件 替换 问题解决
